backend:
  name: github
  repo: TranHang2601/chuavinhung
  branch: main
  base_url: https://decap-oauth.chuavinhhung.workers.dev
  client_id: Ov23liixP8ONSVZfah6H
  site_id: https://chuavinhung.chuavinhhung.workers.dev

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "posts"
    label: "Bài viết & Tin tức"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Tiêu đề", name: "title", widget: "string"}
      - {label: "Ngày đăng", name: "date", widget: "datetime"}
      - {label: "Hình ảnh", name: "image", widget: "image", required: false}
      - {label: "Nội dung", name: "body", widget: "markdown"}